name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: /www/wwwroot/funding.btecit.tech
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies composer
      run: /www/server/php/83/bin/php /usr/bin/composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install Dependencies npm
      run: npm install
    - name: Generate key
      run: /www/server/php/83/bin/php artisan key:generate
    - name: Clean cache
      run: /www/server/php/83/bin/php artisan optimize:clear
    - name: Directory Permissions Bootstrap
      run: chmod -R 777 storage bootstrap/cache
    - name: Directory Permissions
      run: chmod -R 777 storage public
    - name: Build frontend
      run: npm run build
