name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: /www/wwwroot/funding.btecit.tech
    steps:
    - uses: actions/checkout@v4
    - name: copy source
      run: cp -r /home/clubfunding/actions-runner/_work/ClubFunding/ClubFunding/* /www/wwwroot/funding.btecit.tech/
    - name: Install Dependencies composer
      run: cd /www/wwwroot/funding.btecit.tech/ && /www/server/php/82/bin/php /usr/bin/composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install Dependencies npm
      run: cd /www/wwwroot/funding.btecit.tech/ && npm install
    - name: Generate key
      run: cd /www/wwwroot/funding.btecit.tech/ && /www/server/php/82/bin/php artisan key:generate
    - name: Clean cache
      run: cd /www/wwwroot/funding.btecit.tech/ && /www/server/php/82/bin/php artisan optimize:clear
    - name: Directory Permissions Bootstrap
      run: cd /www/wwwroot/funding.btecit.tech/ && chmod -R 777 storage bootstrap/cache
    - name: Directory Permissions
      run: cd /www/wwwroot/funding.btecit.tech/ && chmod -R 777 storage public
    - name: Build frontend
      run: cd /www/wwwroot/funding.btecit.tech/ && npm run build
